### PR TITLE
Updated SLZ test to leverage on SLZ OCP quickstart instead of rc version

### PR DESCRIPTION
**Pull request by vbontempi**
### Description

Updated SLZ test to leverage on SLZ OCP quickstart instead of rc version
https://github.com/terraform-ibm-modules/terraform-ibm-websphere-liberty-operator/issues/38

In the PR removed previous PR ignore updates/destroy (now useless)
Skipped upgrade test as the change impacts only the SLZ test

### Release required?

- [x] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [X] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by ocofaigh — DISMISSED** [review]

**Comment by vbontempi** [comment]
> @vbontempi can you resolve conflicts again and ping me when its ready for merge

fixed, running tests again

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
